/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cv19.view.body;

import com.cv19.view.components.FindDialog;

/**
 *
 * @author ThaiTran
 */
public class AddForm extends javax.swing.JPanel {

    /**
     * Creates new form Form_manage
     */
    public AddForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        container = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbDOB = new javax.swing.JLabel();
        txtDOB = new javax.swing.JComboBox<>();
        lbAddr = new javax.swing.JLabel();
        txtVill = new javax.swing.JComboBox<>();
        txtDis = new javax.swing.JComboBox<>();
        txtCi = new javax.swing.JComboBox<>();
        lbSta = new javax.swing.JLabel();
        txtSta = new javax.swing.JComboBox<>();
        lbSrc = new javax.swing.JLabel();
        txtSrc = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnChooseSrc = new javax.swing.JButton();
        btnDelSrc = new javax.swing.JButton();
        lbTreat = new javax.swing.JLabel();
        txtTreat = new javax.swing.JComboBox<>();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        container.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        container.setLayout(new java.awt.GridBagLayout());

        lbName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbName.setText("Họ tên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 7, 0, 0);
        container.add(lbName, gridBagConstraints);

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 211;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 10, 0, 0);
        container.add(txtName, gridBagConstraints);

        lbID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbID.setText("CMND/CCCD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 38;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 79;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 18, 0, 0);
        container.add(lbID, gridBagConstraints);

        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 192;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 185;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 140;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 4, 0, 11);
        container.add(txtID, gridBagConstraints);

        lbDOB.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbDOB.setText("Năm sinh");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 7, 0, 0);
        container.add(lbDOB, gridBagConstraints);

        txtDOB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 4, 0, 0);
        container.add(txtDOB, gridBagConstraints);

        lbAddr.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbAddr.setText("Địa chỉ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 7, 0, 0);
        container.add(lbAddr, gridBagConstraints);

        txtVill.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 4, 0, 0);
        container.add(txtVill, gridBagConstraints);

        txtDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 55;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 85;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 6, 0, 0);
        container.add(txtDis, gridBagConstraints);

        txtCi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 116;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 261;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 6, 0, 11);
        container.add(txtCi, gridBagConstraints);

        lbSta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbSta.setText("Trạng thái");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 7, 0, 0);
        container.add(lbSta, gridBagConstraints);

        txtSta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 10, 0, 0);
        container.add(txtSta, gridBagConstraints);

        lbSrc.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbSrc.setText("Nguồn lây nhiễm (nếu có)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 7, 0, 0);
        container.add(lbSrc, gridBagConstraints);

        txtSrc.setEditable(false);
        txtSrc.setBackground(new java.awt.Color(204, 204, 255));
        txtSrc.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 184;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 215;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 10, 0, 0);
        container.add(txtSrc, gridBagConstraints);

        btnAdd.setText("Thêm");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.ipadx = 188;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 7, 1, 0);
        container.add(btnAdd, gridBagConstraints);

        btnReset.setText("Làm mới");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 355;
        gridBagConstraints.ipadx = 202;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 1, 11);
        container.add(btnReset, gridBagConstraints);

        btnChooseSrc.setText("Chọn");
        btnChooseSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseSrcActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 374;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 6, 0, 0);
        container.add(btnChooseSrc, gridBagConstraints);

        btnDelSrc.setText("Xoá");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 375;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 6, 0, 0);
        container.add(btnDelSrc, gridBagConstraints);

        lbTreat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbTreat.setText("Nơi điều trị");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 28;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 6, 0, 0);
        container.add(lbTreat, gridBagConstraints);

        txtTreat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 65;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 312;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 11);
        container.add(txtTreat, gridBagConstraints);

        add(container);
    }// </editor-fold>//GEN-END:initComponents

    private void btnChooseSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseSrcActionPerformed
        new FindDialog();
    }//GEN-LAST:event_btnChooseSrcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChooseSrc;
    private javax.swing.JButton btnDelSrc;
    private javax.swing.JButton btnReset;
    private javax.swing.JPanel container;
    private javax.swing.JLabel lbAddr;
    private javax.swing.JLabel lbDOB;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSrc;
    private javax.swing.JLabel lbSta;
    private javax.swing.JLabel lbTreat;
    private javax.swing.JComboBox<String> txtCi;
    private javax.swing.JComboBox<String> txtDOB;
    private javax.swing.JComboBox<String> txtDis;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSrc;
    private javax.swing.JComboBox<String> txtSta;
    private javax.swing.JComboBox<String> txtTreat;
    private javax.swing.JComboBox<String> txtVill;
    // End of variables declaration//GEN-END:variables
}
