/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cv19.view.body;

/**
 *
 * @author ThaiTran
 */
public class FindForm extends javax.swing.JPanel {

    /**
     * Creates new form FindForm
     */
    public FindForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbSta = new javax.swing.JLabel();
        txtSta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        panelResult = new javax.swing.JPanel();
        tbRelate = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSelect = new javax.swing.JButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelSearch.setLayout(new java.awt.GridLayout(2, 1));

        lbID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbID.setText("CMND/CCCD");
        jPanel1.add(lbID);

        txtID.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel1.add(txtID);

        lbName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName.setText("Họ tên");
        lbName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        jPanel1.add(lbName);

        txtName.setMinimumSize(new java.awt.Dimension(100, 20));
        txtName.setPreferredSize(new java.awt.Dimension(100, 20));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtName);

        lbSta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSta.setText("Trạng thái:");
        lbSta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        jPanel1.add(lbSta);

        txtSta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(txtSta);

        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 40));
        jPanel1.add(jLabel4);

        btnSearch.setText("Tìm kiếm");
        jPanel1.add(btnSearch);

        panelSearch.add(jPanel1);

        add(panelSearch);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        panelResult.setLayout(flowLayout1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CMND/CCCD", "Họ tên", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRelate.setViewportView(jTable1);

        panelResult.add(tbRelate);

        btnSelect.setText("Chọn");
        panelResult.add(btnSelect);

        add(panelResult);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSta;
    private javax.swing.JPanel panelResult;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JScrollPane tbRelate;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox<String> txtSta;
    // End of variables declaration//GEN-END:variables
}
