/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cv19.view.body;

import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ThaiTran
 */
public class ManageForm extends javax.swing.JPanel {

    /**
     * Creates new form ManageForm
     */
    public ManageForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHead = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbDob = new javax.swing.JLabel();
        txtDob = new javax.swing.JComboBox<>();
        lbSta = new javax.swing.JLabel();
        txtSta = new javax.swing.JComboBox<>();
        lbAddr = new javax.swing.JLabel();
        txtVil = new javax.swing.JComboBox<>();
        txtDis = new javax.swing.JComboBox<>();
        txtCi = new javax.swing.JComboBox<>();
        lbTreat = new javax.swing.JLabel();
        txtTreat = new javax.swing.JComboBox<>();
        panelBtn = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        scTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelHead.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin"));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5);
        flowLayout1.setAlignOnBaseline(true);
        panelHead.setLayout(flowLayout1);

        panelInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbName.setText("Họ tên");
        panelInput.add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        txtName.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelInput.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 11, 216, 30));

        lbID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbID.setText("CMND/CCCD");
        panelInput.add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 15, -1, -1));

        txtID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelInput.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 11, 133, 30));

        lbDob.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbDob.setText("Năm sinh");
        panelInput.add(lbDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        txtDob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelInput.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 60, 81, -1));

        lbSta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbSta.setText("Trạng thái");
        panelInput.add(lbSta, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 59, -1, -1));

        txtSta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtSta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStaActionPerformed(evt);
            }
        });
        panelInput.add(txtSta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 81, -1));

        lbAddr.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbAddr.setText("Địa chỉ");
        panelInput.add(lbAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, 64, -1));

        txtVil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelInput.add(txtVil, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 99, 141, -1));

        txtDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelInput.add(txtDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 99, 142, -1));

        txtCi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelInput.add(txtCi, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 99, 157, -1));

        lbTreat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbTreat.setText("Nơi điều trị ");
        panelInput.add(lbTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, -1, -1));

        txtTreat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtTreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTreatActionPerformed(evt);
            }
        });
        panelInput.add(txtTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 250, -1));

        panelHead.add(panelInput);

        panelBtn.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        btnSearch.setText("Tìm kiếm");
        btnSearch.setFocusable(false);
        panelBtn.add(btnSearch);

        btnReset.setText("Làm mới");
        btnReset.setFocusable(false);
        panelBtn.add(btnReset);

        btnDel.setText("Xoá");
        btnDel.setFocusable(false);
        panelBtn.add(btnDel);

        panelHead.add(panelBtn);

        add(panelHead);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CMND/CCCD", "Họ tên", "Năm sinh", "Địa chỉ", "Trạng Thái", "Nơi điều trị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scTable.setViewportView(table);

        add(scTable);
    }// </editor-fold>//GEN-END:initComponents

    private void txtStaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStaActionPerformed

    private void txtTreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTreatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTreatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lbAddr;
    private javax.swing.JLabel lbDob;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSta;
    private javax.swing.JLabel lbTreat;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelInput;
    private javax.swing.JScrollPane scTable;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> txtCi;
    private javax.swing.JComboBox<String> txtDis;
    private javax.swing.JComboBox<String> txtDob;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JComboBox<String> txtSta;
    private javax.swing.JComboBox<String> txtTreat;
    private javax.swing.JComboBox<String> txtVil;
    // End of variables declaration//GEN-END:variables
}
