/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cv19.view.body;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;

/**
 *
 * @author ThaiTran
 */
public class NecessityForm extends javax.swing.JPanel {

    /**
     * Creates new form NecessityForm
     */
    public NecessityForm() {
        initComponents();
        table.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent mouseEvent) {
                JTable table = (JTable) mouseEvent.getSource();
                Point point = mouseEvent.getPoint();
                int row = table.rowAtPoint(point);
                if (mouseEvent.getClickCount() == 2 && table.getSelectedRow() != -1) {
                    // your valueChanged overridden method 
                    System.out.println("table row: "+row);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        lbPackIn = new javax.swing.JLabel();
        txtPackIn = new javax.swing.JTextField();
        lbLimitIn = new javax.swing.JLabel();
        txtLimitIn = new javax.swing.JSpinner();
        lbTimeIn = new javax.swing.JLabel();
        txtTimeIn = new javax.swing.JComboBox<>();
        panelBtn = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        taNotify = new javax.swing.JTextArea();
        panelFind = new javax.swing.JPanel();
        lbPack = new javax.swing.JLabel();
        txtPack = new javax.swing.JTextField();
        lbTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JComboBox<>();
        lbSort = new javax.swing.JLabel();
        txtSort = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        scTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        panelTop.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm/xoá/sửa"));
        panelTop.setPreferredSize(new java.awt.Dimension(1001, 80));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5);
        flowLayout1.setAlignOnBaseline(true);
        panelTop.setLayout(flowLayout1);

        panelInput.setLayout(new java.awt.GridLayout(3, 3, 4, 10));

        lbPackIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPackIn.setText("Tên gói :");
        panelInput.add(lbPackIn);
        panelInput.add(txtPackIn);

        lbLimitIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbLimitIn.setText("Mức giới hạn :");
        panelInput.add(lbLimitIn);
        panelInput.add(txtLimitIn);

        lbTimeIn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTimeIn.setText("Thời gian giới hạn :");
        panelInput.add(lbTimeIn);

        txtTimeIn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelInput.add(txtTimeIn);

        panelTop.add(panelInput);

        panelBtn.setLayout(new java.awt.GridLayout(3, 1, 20, 10));

        btnAdd.setText("Thêm");
        panelBtn.add(btnAdd);

        btnDel.setText("Xoá");
        panelBtn.add(btnDel);

        btnUpdate.setText("Sửa");
        panelBtn.add(btnUpdate);

        panelTop.add(panelBtn);

        taNotify.setEditable(false);
        taNotify.setColumns(40);
        taNotify.setLineWrap(true);
        taNotify.setRows(5);
        taNotify.setText(">>>Thông tin");
        panelTop.add(taNotify);

        add(panelTop);

        panelFind.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));
        panelFind.setPreferredSize(new java.awt.Dimension(755, 30));
        panelFind.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbPack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPack.setText("Tên gói :");
        panelFind.add(lbPack);

        txtPack.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 50), null));
        txtPack.setMargin(new java.awt.Insets(2, 2, 2, 10));
        txtPack.setPreferredSize(new java.awt.Dimension(150, 25));
        txtPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPackActionPerformed(evt);
            }
        });
        panelFind.add(txtPack);

        lbTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTime.setText("Thời gian giới hạn : ");
        lbTime.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        panelFind.add(lbTime);

        txtTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelFind.add(txtTime);

        lbSort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSort.setText("Sắp xếp theo :");
        lbSort.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        panelFind.add(lbSort);

        txtSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelFind.add(txtSort);

        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 30));
        panelFind.add(jLabel7);

        btnFind.setText("Tìm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });
        panelFind.add(btnFind);

        add(panelFind);

        scTable.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Phổ thông", "3 gói", "1 tuần", "20.000", null}
            },
            new String [] {
                "Tên gói", "Mức giới hạn", "Thời gian giới hạn", "Đơn giá", "Lượng tiêu thụ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        scTable.setViewportView(table);

        add(scTable);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFindActionPerformed

    private void txtPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbLimitIn;
    private javax.swing.JLabel lbPack;
    private javax.swing.JLabel lbPackIn;
    private javax.swing.JLabel lbSort;
    private javax.swing.JLabel lbTime;
    private javax.swing.JLabel lbTimeIn;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelFind;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelTop;
    private javax.swing.JScrollPane scTable;
    private javax.swing.JTextArea taNotify;
    private javax.swing.JTable table;
    private javax.swing.JSpinner txtLimitIn;
    private javax.swing.JTextField txtPack;
    private javax.swing.JTextField txtPackIn;
    private javax.swing.JComboBox<String> txtSort;
    private javax.swing.JComboBox<String> txtTime;
    private javax.swing.JComboBox<String> txtTimeIn;
    // End of variables declaration//GEN-END:variables
}
