/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cv19.view.body;

/**
 *
 * @author ThaiTran
 */
public class OutBalanceForm extends javax.swing.JPanel {

    /**
     * Creates new form OutBalanceForm
     */
    public OutBalanceForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbSort = new javax.swing.JLabel();
        txtSort = new javax.swing.JComboBox<>();
        lbSpace = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        scTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panelBottom = new javax.swing.JPanel();
        lbTotal = new javax.swing.JLabel();
        lbTotalCalc = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lbID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbID.setText("Tìm dư nợ theo cmnd/cccd:");
        panelTop.add(lbID);

        txtID.setPreferredSize(new java.awt.Dimension(100, 20));
        panelTop.add(txtID);

        lbSort.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSort.setText("Sắp xếp theo:");
        lbSort.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        panelTop.add(lbSort);

        txtSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Chọn kiểu sắp xếp>" }));
        panelTop.add(txtSort);

        lbSpace.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 30));
        panelTop.add(lbSpace);

        btnFind.setText("Truy xuất");
        panelTop.add(btnFind);

        add(panelTop);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CMND/CCCD", "HỌ TÊN", "ĐỊA CHỈ", "DƯ NỢ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scTable.setViewportView(table);

        add(scTable);

        panelBottom.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTotal.setText("Tổng dư nợ :");
        panelBottom.add(lbTotal);

        lbTotalCalc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTotalCalc.setText("0đ");
        panelBottom.add(lbTotalCalc);

        add(panelBottom);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbSort;
    private javax.swing.JLabel lbSpace;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbTotalCalc;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelTop;
    private javax.swing.JScrollPane scTable;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtID;
    private javax.swing.JComboBox<String> txtSort;
    // End of variables declaration//GEN-END:variables
}
