/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.cv19.view.body;

import com.cv19.view.components.FindDialog;

/**
 *
 * @author ThaiTran
 */
public class ViewDetailForm extends javax.swing.JPanel {

    /**
     * Creates new form ViewDetailForm
     */
    public ViewDetailForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTop = new javax.swing.JPanel();
        lbHeader = new javax.swing.JLabel();
        panelMid = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        lbID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lbName = new javax.swing.JLabel();
        txtSrc = new javax.swing.JTextField();
        lbAddr = new javax.swing.JLabel();
        txtVill = new javax.swing.JComboBox<>();
        txtDis = new javax.swing.JComboBox<>();
        txtCi = new javax.swing.JComboBox<>();
        lbSta = new javax.swing.JLabel();
        txtSta = new javax.swing.JComboBox<>();
        lbTreat = new javax.swing.JLabel();
        txtTreat = new javax.swing.JComboBox<>();
        lbSrc = new javax.swing.JLabel();
        btnSrc = new javax.swing.JButton();
        btnDelSrc = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        panelBtn = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        lbTable = new javax.swing.JLabel();
        scTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        lbHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbHeader.setText("Thông tin chi tiết");
        panelTop.add(lbHeader);

        add(panelTop);

        panelInput.setLayout(new java.awt.GridBagLayout());

        lbID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbID.setText("CMND/CCCD:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 0, 0);
        panelInput.add(lbID, gridBagConstraints);

        txtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        panelInput.add(txtID, gridBagConstraints);

        lbName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbName.setText("Họ tên:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 18, 0, 0);
        panelInput.add(lbName, gridBagConstraints);

        txtSrc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 39;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 201;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        panelInput.add(txtSrc, gridBagConstraints);

        lbAddr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbAddr.setText("Địa chỉ:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        panelInput.add(lbAddr, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        panelInput.add(txtVill, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        panelInput.add(txtDis, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 17;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 27;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        panelInput.add(txtCi, gridBagConstraints);

        lbSta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSta.setText("Trạng thái:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        panelInput.add(lbSta, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        panelInput.add(txtSta, gridBagConstraints);

        lbTreat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTreat.setText("Nơi điều trị:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 0);
        panelInput.add(lbTreat, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 225;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 2, 0, 0);
        panelInput.add(txtTreat, gridBagConstraints);

        lbSrc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSrc.setText("Nguồn lây nhiễm (nếu có)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 10, 0, 0);
        panelInput.add(lbSrc, gridBagConstraints);

        btnSrc.setText("Chọn");
        btnSrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSrcActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 61;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        panelInput.add(btnSrc, gridBagConstraints);

        btnDelSrc.setText("Xoá");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 62;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 41;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 6, 0, 0);
        panelInput.add(btnDelSrc, gridBagConstraints);

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 40;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 157;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 0);
        panelInput.add(txtName, gridBagConstraints);

        panelMid.add(panelInput);

        panelBtn.setLayout(new java.awt.GridLayout(4, 1, 0, 10));

        btnUpdate.setText("Cập nhật");
        panelBtn.add(btnUpdate);

        btnDel.setText("Xoá");
        panelBtn.add(btnDel);

        panelMid.add(panelBtn);

        add(panelMid);

        lbTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTable.setText("Danh sách người liên quan");
        panelTable.add(lbTable);

        add(panelTable);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CMND/CCCD", "CMND/CCCD[lây nhiễm từ]", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scTable.setViewportView(table);

        add(scTable);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSrcActionPerformed
        new FindDialog();
    }//GEN-LAST:event_btnSrcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDelSrc;
    private javax.swing.JButton btnSrc;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lbAddr;
    private javax.swing.JLabel lbHeader;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbSrc;
    private javax.swing.JLabel lbSta;
    private javax.swing.JLabel lbTable;
    private javax.swing.JLabel lbTreat;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelMid;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelTop;
    private javax.swing.JScrollPane scTable;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> txtCi;
    private javax.swing.JComboBox<String> txtDis;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSrc;
    private javax.swing.JComboBox<String> txtSta;
    private javax.swing.JComboBox<String> txtTreat;
    private javax.swing.JComboBox<String> txtVill;
    // End of variables declaration//GEN-END:variables
}
